name: api CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Requirements.txt
        pip install pytest fastapi requests httpx 

    - name: Run tests
      env:
        USERNAME: ${{ secrets.API_USERNAME }}
        PASSWORD: ${{ secrets.API_PASSWORD }}
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest tests/test_api.py

    - name: Build Docker image
      run: docker build -t yotam433/palindrome-api:latest -f docker/DockerFile .

    - name: Log in to Docker Hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image to Docker Hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: docker push yotam433/palindrome-api:latest